# Generated by Django 5.0.7 on 2024-07-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
