# Generated by Django 5.0.7 on 2024-07-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_maintenance_service_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecompanyuser',
            name='cars',
            field=models.ManyToManyField(blank=True, to='vehicles.car', verbose_name='Машины'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to='vehicles.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehicles.userprofile', verbose_name='Клиент'),
        ),
    ]
